### ISSUE TITLE
Unit spawning(Suggestion/Problem)

### ISSUE THREAD

**Issue by JonniAV** [olandra/CBSafe-Simulation#19]
When unit spawns, it is spawned to closest spawn position to place of accident and only spawns unit available to that spawn.
Is it possible to add spawn link to unit where it spawns or shall we leave that option for later?

**Comment by olandra** [comment]
This feature has been implemented.

The event call for units takes a vector. This position is compered to the spawns and the closest applicable spawn is used. UI can implement this in several ways, for example by listing the spawn positions and using those with the event call.

The TestingUI implements this feature by allowing the tester to pass a target set by the third mouse button. This provides more flexibility for testing, which is not necessarily needed for players.
