### ISSUE TITLE
Stuck on "Get Hose State"

### ISSUE THREAD

**Issue by OKAllu** [olandra/CBSafe-Simulation#21]
Issuing fire extinguish command
-> AI goes to "Firefighter Get Hose State" and gets stuck there
   -> At the same time driver keeps repeating "Firefighter Take Off Swimming Suit State" 
![image](https://user-images.githubusercontent.com/98382332/186112142-1b7c7990-0f74-45df-9866-52fa69e1770f.png)

**Comment by olandra** [comment]
Added extra comparison for driver in Firefighter Walk State. Should be fixed in changeset 699.
