### ISSUE TITLE
Unit spawn and command event

### ISSUE THREAD

**Issue by JonniAV** [olandra/CBSafe-Simulation#22]
When unit is called and does not have a spawn point to be instantiated in -> when adding a spawn as evaluator then the called unit immediately spawns to this marker even if not yet set. When adding a destination after, the unit does not start moving.

When trying to give command to unit that instantiated, the unit does not follow the command(maybe because unit didn't have a destinations to follow)

Additional info: Markers are still in pawn form and visible to master when this happens.
With already existing spawns it seems that new spawn marker and setting for it to give vector position to UnitDestinations, it seems to not take note of the new setting and spawns with the already existing spawn.

**Comment by olandra** [comment]
It'd appear that the called unit remains in the queue until a spawn can be found.

Changeset 711 addresses this by adding a safeguard around unit instantiation and resets the unit call time if no free spawns or destinations are found.
