### ISSUE TITLE
Hose (letku) isn't connected to the part in npc's hand (suutin)

### ISSUE THREAD

**Issue by OKAllu** [olandra/CBSafe-Simulation#45]
- Happens only with 101 (202 is fine)
- Happens every time (tested multiple times)
- Picture for reference
![image](https://user-images.githubusercontent.com/98382332/190369199-a32b8a26-f78e-4f71-b3e8-2cd67c99fc43.png)

**Comment by olandra** [comment]
Could try to fix this by taking the first member from 202 and replacing it in 101 as it works nicely in 202

**Comment by olandra** [comment]
Fixed in changeset 812
