### ISSUE TITLE
Gets stuck if issuing command too early (Tested with player UI)

### ISSUE THREAD

**Issue by OKAllu** [olandra/CBSafe-Simulation#9]
If you issue a rescue command while the unit is still arriving and not stopped yet, the members wont come out of the car and the car stays stuck.
However search commands work if given before the unit arrives.

**Comment by olandra** [comment]
This happens because the CarDrive state compares against aiUnitInfo.Order for exit condition. Need to either give the car a new variable or enum to represent it's orders.

**Comment by olandra** [comment]
Fixed in Changeset 287
